### ISSUE TITLE
GeoJSON data is not correct, fails to plot

### ISSUE THREAD

**Issue by kasim-rafay** [EngineeredVirus/PakistanMap#1]
Thanks for this upload. But there's some issue with this GeoJSON - it's not a valid JSON first of all (some comma missing). I added the missing commas and put all the `Feature` objects in an array but it still doesn't show up on the map. Github can't preview it either, plus I couldn't get it plot in react-simple-maps.

**Comment by hqakhtar** [comment]
Fixed the issue with GeoJSON and verified that it plots fine in leaflet.
